// Stub for Prisma client - real client will be generated by Backend Developer
// This allows the frontend to build without a database connection

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const prisma: any = {};
export { prisma };